import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});



export const metadata = {
  title: "Creativolve Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body
        className={`${montserrat.variable} antialiased bg-[#171717]`}

      >
        {children}
      </body>
    </html>
  );
}
